### ISSUE TITLE
Upload failed

### ISSUE THREAD

**Issue by leonguyen52** [duythongle/fshare2gdrive#1]
2019/05/13 21:38:50 "gdrive:/Upload/" is a directory

Khi mình tiến hành chạy lệnh như hướng dẫn thì nó báo lỗi như vậy. Liệu có phải do nó ko đọc được tên file cần upload?

**Comment by duythongle** [comment]
Bạn nên dẫn command và output cụ thể ra luôn (copy & paste từ terminal) để mọi người dễ theo dõi. Chứ báo lỗi khơi khơi thế này mình cũng bó tay.

**Comment by leonguyen52** [comment]
Mình sửa lại được rồi. Cảm ơn bạn nhiều.
Cho mình hỏi là liệu có cách nào extract link folder fshare thành từng link file để tải cả list không nhỉ? Hiện tại tải từng link đơn lẻ thì rất ok rồi.

**Comment by duythongle** [comment]
Chưa support nhé. Nếu thích bạn cứ gen ra list các câu lệnh download tương ứng rồi cho chạy hàng loạt song song hay tuần tự tùy bạn.
