### ISSUE TITLE
Replace api2.fshare.vn with api.fshare.vn in fshare2gdrive.js

### ISSUE THREAD

**Issue by mra00000** [duythongle/fshare2gdrive#10]
I tried to use the source from the repo to sign in but failed all the time
After doing some research, i finally found that api2.fshare.vn will just return a 400 error code, maybe this api is deprecated ?
Replacing api2.fshare.vn with api.fshare.vn in fshare2gdrive.js file will get everything back working again
![222](https://user-images.githubusercontent.com/4137960/71425520-95699880-26d0-11ea-9398-cecc47d44b15.png)

**Comment by duythongle** [comment]
Thanks. It seems FShare's been rolling back to their old API. That's weird! I'll fix it soon.
