### ISSUE TITLE
Raspbian Request: Xin HD chạy fshare2gdrive headless SSH

### ISSUE THREAD

**Issue by kodavn** [duythongle/fshare2gdrive#15]
Hi anh @duythongle , em run fshare2gdrive trên Raspberry pi 3 headless nên mỗi lần transfer đều phải mở SSH trên windows rồi chờ nó finish mới close SSH session được. Xin anh hd giúp cách nào chạy command xong rồi tắt SSH nó vẫn run tiếp được không ạ. Cảm ơn anh.

**Comment by bienvanhoang** [comment]
> Hi anh @duythongle , em run fshare2gdrive trên Raspberry pi 3 headless nên mỗi lần transfer đều phải mở SSH trên windows rồi chờ nó finish mới close SSH session được. Xin anh hd giúp cách nào chạy command xong rồi tắt SSH nó vẫn run tiếp được không ạ. Cảm ơn anh.
Tìm hiểu tmux nha

**Comment by kodavn** [comment]
> > Hi anh @duythongle , em run fshare2gdrive trên Raspberry pi 3 headless nên mỗi lần transfer đều phải mở SSH trên windows rồi chờ nó finish mới close SSH session được. Xin anh hd giúp cách nào chạy command xong rồi tắt SSH nó vẫn run tiếp được không ạ. Cảm ơn anh.
> 
> Tìm hiểu tmux nha

cảm ơn anh tư vấn
