### ISSUE TITLE
Cannot login Fshare recently

### ISSUE THREAD

**Issue by jonidontcry** [duythongle/fshare2gdrive#18]
![Untitled](https://user-images.githubusercontent.com/64350078/80570448-fc071600-8a24-11ea-83c7-15314273b170.png)
I cannot login to Fshare recently. Account is VIP already.
However, another friend can login successfully.
What could be the problem here? Thank you.

**Comment by duythongle** [comment]
> ![Untitled](https://user-images.githubusercontent.com/64350078/80570448-fc071600-8a24-11ea-83c7-15314273b170.png)
> I cannot login to Fshare recently. Account is VIP already.
> However, another friend can login successfully.
> What could be the problem here? Thank you.

Your FShare account is not VIP OR you have been block from FShare
