### ISSUE TITLE
Lỗi khi FS có tên file đặt dấu cách

### ISSUE THREAD

**Issue by epubc** [duythongle/fshare2gdrive#2]
Mình thử thì thấy tool này quá hoàn hảo tuy nhiên có 1 bug nhỏ là khi tập tin Fshare có khoảng cách như [Tap Tin.mkv] thì nó chỉ nhận diện được ký tự Tap và khi upload lên gdrive thì chỉ có tên là Tap mà không có định dạng.

**Comment by duythongle** [comment]
Bạn cung cấp link fshare lỗi mình test. Hiện mình chạy lệnh dưới để upload file "spaces spaces.txt" lên gdrive OK.

`curl -s https://duythongle.github.io/fshare2gdrive/download.sh | bash -s "https://www.fshare.vn/file/K99BH7AIEAXI" "my-remote-gdrive" "/"`

**Comment by epubc** [comment]
> Bạn cung cấp link fshare lỗi mình test. Hiện mình chạy lệnh dưới để upload file "spaces spaces.txt" lên gdrive OK.
> 
> ```shell
> $ curl -s https://duythongle.github.io/fshare2gdrive/download.sh | bash -s "https://www.fshare.vn/file/K99BH7AIEAXI?token=1559160696" "my-remote-gdrive" "/"
> http://download001.fshare.vn/dl/zTGtkrm0VwaXklKiJhk-7hnf8mBevY2fDqmWSJUtY3-Qr8cBH+wCJCBOPb4wIq3d9e93P9zKOq8snxn3/spaces                    paces.txt
> - https://www.fshare.vn/file/K99BH7AIEAXI - Found VIP download link: http://download001.fshare.vn/dl/zTGtkrm0VwaXklKiJhk-7hnf8mBevY2fDqmWSJUtY3-Qr8cBH+wCJCBOPb4wIq3d9e93P9zKOq8snxn3/spaces                    paces.txt
> - Uploading http://download001.fshare.vn/dl/zTGtkrm0VwaXklKiJhk-7hnf8mBevY2fDqmWSJUtY3-Qr8cBH+wCJCBOPb4wIq3d9e93P9zKOq8snxn3/spaces                    paces.txt to my-remote-gdrive:/spaces spaces.txt. Please wait...
> ```

Cám ơn bạn đã trả lời.
Bug mình gặp ở đây kiểu như hiển thị tên file không được trọn vẹn.

> curl -s https://duythongle.github.io/fshare2gdrive/download.sh | bash -s "https://www.fshare.vn/file/X5MH7BQHXXOB8VJ?token=1559177441" "linuxteam" "/FVN/"
main: line 20: printf: `D': invalid format character
http://download024.fshare.vn/dl/iOiBxWjCwzTAt7y6NXI9ywKohJHoBTJCz3Y5EOQVlo-fh+GymEjDz7XHFfg5zEkVHW6UQe-dxTElEMiQ/Tinhmain: line 27: printf: `D': invalid format character
- https://www.fshare.vn/file/X5MH7BQHXXOB8VJ - Found VIP download link: http://download024.fshare.vn/dl/iOiBxWjCwzTAt7y6NXI9ywKohJHoBTJCz3Y5EOQVlo-fh+GymEjDz7XHFfg5zEkVHW6UQe-dxTElEMiQ/Tinhmain: line 28: printf: `D': invalid format character
- Uploading http://download024.fshare.vn/dl/iOiBxWjCwzTAt7y6NXI9ywKohJHoBTJCz3Y5EOQVlo-fh+GymEjDz7XHFfg5zEkVHW6UQe-dxTElEMiQ/Tinh
