### ISSUE TITLE
tốc độ down load rất chậm

### ISSUE THREAD

**Issue by starchbmt** [duythongle/fshare2gdrive#20]
bác ơi em hỏi với, e xài script của bác trên gg vps lẫn azure tốc độ chỉ được 800kb/s server singapore bác biết tại sao không ạ

**Comment by duythongle** [comment]
Do nhiều nguyên nhân:
- Script chỉ dùng một kết nối để transfer.
- Cá mập cắn cáp.
- Server có đường truyền kém
