### ISSUE TITLE
Fshare API changed, can not login

### ISSUE THREAD

**Issue by usphil** [duythongle/fshare2gdrive#26]
Script transfer file từ Fshare báo lỗi "Retry request /api/user/login with wait time 2s..." là do thư viện API của Fshare thay đổi.

Mong tác giả DuyThongLe bỏ chút thì giờ fix cho anh em được sử dụng cái program quá tuyệt này.

**Comment by hoangtu21488** [comment]
mong bác fix sớm. Thanks

**Comment by usphil** [comment]
Thanks sntran for your fix

**Comment by diephongyen** [comment]
em vẫn không llogin dc mấy anh ơi

**Comment by usphil** [comment]
> em vẫn không llogin dc mấy anh ơi

Bạn chưa login được là vì tác giả DuyThongLe chua fix file https://raw.githubusercontent.com/duythongle/fshare2gdrive/master/fshare2gdrive.js.
Theo hướng dẫn của sntran, bạn phải tao file fshare2drive.js fixed và upload lên một server nào đó để thay thế file của DuyThongLe.

ví dụ dòng lịnh để login fshare sẽ như vầy: 

curl -sS https://filedn.com/lXWPrdig4/tsswVFgor/fshare2gdrive.js | \
tail -n+2 | node - login "fshare@gmail.net" "VN2020" 

các đường link và username password chỉ là ví dụ

**Comment by diephongyen** [comment]
Thank mấy anh, cuối cùng cũng login dc rồi

**Comment by tien-nguyen12** [comment]
Cảm ơn vì đã fix ạ!

**Comment by duythongle** [comment]
Thank @sntran for your quick fix! Dạo này lu bu công việc với hóng bầu cử Mỹ quá :sweat_smile:
