### ISSUE TITLE
Add Change md5 file.

### ISSUE THREAD

**Issue by nghiadht** [duythongle/fshare2gdrive#5]
Chào bác,
Với các file video phim bản quyền thì có khả năng sẽ bị cắm cờ nếu không change md5 của file. Bác bổ sung tính năng này nữa thì tuyệt vời :D

**Comment by duythongle** [comment]
Nếu bác biết cách change MD5 hash của file trên linux thì gợi ý mình nhé. Theo mình biết thì change MD5 hash của file sẽ bị rủi ro hư file (tùy theo file format).

**Comment by nghiadht** [comment]
Mình có change md5 bằng tools này nhưng k thấy thay đổi dung lượng file.
https://github.com/ewwink/MD5-Hash-Changer
Gửi bác xem thử, còn change trên linux mình không rõ :D

**Comment by duythongle** [comment]
Vậy thì khó rồi. Vả lại tiêu chí là ko lưu file để tiết kiệm chi phí VPS thì change hash khó khả thi lắm (vì cần lưu file)

**Comment by nghiadht** [comment]
Ok cảm ơn bác

Vào Th 4, 7 thg 8, 2019 vào lúc 10:45 Thong Duy Le <
notifications@github.com> đã viết:
