### ISSUE TITLE
Unstable 400 error from fshare API

### ISSUE THREAD

**Issue by hieuvn** [duythongle/fshare2gdrive#7]
Dạo này login hay bị lỗi 400, phải thử 2 -3 lần mới thành công, mình đặt lênh tự đọng trong crontab mỗi lần login fails là nó ngưng luôn
![image](https://user-images.githubusercontent.com/14049725/67835048-912f5d80-fb1b-11e9-8b20-371172e4244d.png)

**Comment by duythongle** [comment]
Do bên fshare server nâng cấp hệ thống hay sao đó

**Comment by hieuvn** [comment]
mình thì nghi nhà mạng bị tác động (bóp,chặn...) vào những ngày cuối tuần, nhũng ngày này các service cua google hoạt động cũng không ổn định.
bạn có thể chỉnh code lại cho chạy vòng lặp đến khi nào login được thì thôi hoặc cho lặp từ 1-10 chẳng hạn?

**Comment by ctnhobb** [comment]
chiều rảnh em sẽ debug cái này ạ

**Comment by hieuvn** [comment]
khi tải folder mà login failed, nếu mình login lại thì sẽ bị upload trùng item đã up lên trong phiên giao dịch trước, bạn @duythongle  xem lại dùm vấn đề này với. Cảm ơn bạn

**Comment by duythongle** [comment]
@hieuvn Hiện mình muốn giữ code tối giản, ko kiểm soát upload trùng hay xử lý faillover vì những vấn đề này có thể xử lý được bằng Linux. Ví dụ:
 - Kiểm soát scheduler bằng [systemd](https://medium.com/horrible-hacks/using-systemd-as-a-better-cron-a4023eea996d)
 - Tự dò những file đã upload rồi bỏ qua bằng cách adjust `tail n+X` khi chạy lệnh upload folder...

**Comment by hieuvn** [comment]
> * Tự dò những file đã upload rồi bỏ qua bằng cách adjust `tail n+X` khi chạy lệnh upload folder...
mình mới tìm hiểu linux nên còn bỡ ngỡ, bạn cho mình ví dụ về trường hợp này đi. Cảm ơn

**Comment by duythongle** [comment]
Now support auto-retry (10 times with increment wait time) at latest commit 0286cc3
Let me know if you would like to retry infinite times or just adjust retry time, depends on a common use case.

**Comment by duythongle** [comment]
Tạm thời cập nhật unlimited retry (2s wait time) xem thế nào 01c1ac5.

**Comment by thinhplust** [comment]
![Screenshot_20191107-084557](https://user-images.githubusercontent.com/22842481/68353084-11b51600-013b-11ea-9d60-1f5e8be92e3d.png)
Chắc tạm thời nghỉ ngơi thôi bác nhỉ

**Comment by hieuvn** [comment]
hôm qua (06-nov) code sửa lần đàu chạy ok, hôm nay chưa test

**Comment by KangHidro** [comment]
hình như lỗi này https://github.com/duythongle/fshare2gdrive/issues/7#issuecomment-550582114 vẫn chưa fix được hả các bác

**Comment by duythongle** [comment]
@KangHidro Lỗi do FShare server chập chờn

**Comment by KangHidro** [comment]
@duythongle Vâng bác, em tải bình thường nó còn hay bị lỗi DNS gì gì ấy nữa mà, chắc Fs định cải tiến gì mới 😂

**Comment by taimaiduc** [comment]
@duythongle Still not working....
![image](https://user-images.githubusercontent.com/10907980/71656227-2560af80-2d6d-11ea-9d23-a26c8f485df9.png)

**Comment by vinhvgs** [comment]
> * systemd
Tự dò những file đã upload rồi bỏ qua bằng cách adjust tail n+X khi chạy lệnh upload folder..
Bạn có thể chỉ rõ hơn cái này giúp mình được k bạn?

**Comment by nguyenhuy189** [comment]
Bác @duythongle fix lại code giúp đc kg ạ? Fshare lại đổi api nữa hay sao???
Cám ơn bác.

Lỗi như này:
Retry request /api/user/login with wait time 2s...
Retry request /api/user/login with wait time 2s...
Retry request /api/user/login with wait time 2s...
Retry request /api/user/login with wait time 2s...
Retry request /api/user/login with wait time 2s...

**Comment by ctnhobb** [comment]
@duythongle  Em Huy Còi đây ạ
sáng em có debug dùm bạn em thì 
01 api fshare thi thoảng trả về httpcode 400
02 lúc login bạn em bị httpcode 520 nên nó báo Retry request /api/user/login with wait time 2s..
tạm thời em chưa có thêm thông tin gì :D

**Comment by ctnhobb** [comment]
code getlink php của synology vẫn getlink ổn ạ


log của code getlink synology

[INFO] - 2020-12-12 09:20:05 - Start getting download info
[INFO] - 2020-12-12 09:20:05 - Checking if need to re-login
[INFO] - 2020-12-12 09:20:05 - Token is empty => need to login to get token
[INFO] - 2020-12-12 09:20:05 - Cookie file is not existed => need to login to get cookie
[INFO] - 2020-12-12 09:20:05 - Start login
[INFO] - 2020-12-12 09:20:09 - HTTP Response: {"code":200,"msg":"Login successfully!","token":".....................","session_id":"........................."}
[INFO] - 2020-12-12 09:20:09 - HTTP CODE: 200
[INFO] - 2020-12-12 09:20:09 - CODE: 200
[INFO] - 2020-12-12 09:20:09 - Login ok
[INFO] - 2020-12-12 09:20:09 - End login
[INFO] - 2020-12-12 09:20:09 - Start Get Link: https://www.fshare.vn/file/.........
[INFO] - 2020-12-12 09:20:16 - HTTP Response: {"location":"http:\/\/download022.fshare.vn\/dl\/............\/youtube1080.rar"}
[INFO] - 2020-12-12 09:20:16 - HTTP CODE: 200
[INFO] - 2020-12-12 09:20:16 - CODE: 
[INFO] - 2020-12-12 09:20:16 - Get link ok
[INFO] - 2020-12-12 09:20:16 - End Get Link
[INFO] - 2020-12-12 09:20:16 - End getting download info
[INFO] - 2020-12-12 09:20:16 - =========================================================

**Comment by qthang** [comment]
Hiện tại mình cũng đang bị lỗi **Retry request /api/user/login with wait time 2s...**
