### ISSUE TITLE
Lỗi login Fshare. 

### ISSUE THREAD

**Issue by thinhplust** [duythongle/fshare2gdrive#8]
Tính hình ko khả quan là mấy a ơi. auto-retry 10 lần có vẻ vẫn ko ăn thua.
![Screenshot_20191107-021533](https://user-images.githubusercontent.com/22842481/68329842-bb2ce500-0104-11ea-992d-980c4d256fb2.png)

**Comment by duythongle** [comment]
Trao đổi chung bên này nhé #7 .  Same bug.
