### ISSUE TITLE
Retry request /api/user/login with wait time 2s...

### ISSUE THREAD

**Issue by sonmagician** [duythongle/fshare2gdrive#9]
![Capture](https://user-images.githubusercontent.com/41722936/71029654-6c7e5c00-2142-11ea-89d0-c664d69bef24.PNG)
Anh fix lỗi này ạ

**Comment by duythongle** [comment]
Uhm, cùng lỗi với #7 .  Qua đó hóng nhé. Nói chung do FShare server chập chờn tùy thời điểm. Cứ để nó tự động retry sẽ có lúc OK.
